### ISSUE TITLE
issue starting on fedora

### ISSUE THREAD

**Issue by jnaulty** [urish/muse-js#3]
Hey, I'm trying to test this out on my linux machine. I'm using Fedora 25.
I'm not the best at debugging node/javascript tracebacks. :\
```
[jnaulty@emarginata muse-js]$ yarn --version
1.3.2
[jnaulty@emarginata muse-js]$ npm -v
3.10.10
[jnaulty@emarginata muse-js]$ node -v
v6.12.0
[jnaulty@emarginata muse-js]$ yarn start
yarn run v1.3.2
$ node demo/fuse
app ->
└──  (6 files,  29.5 kB) default
     demo/src/main.js
     src/muse.js
     src/lib/muse-interfaces.js
     src/lib/muse-parse.js
     src/lib/muse-utils.js
     src/lib/zip-samples.js
└── fusebox-hot-reload@0.0.0 1.8 kB (0 files)
└── fusebox-websocket@0.0.0 2.9 kB (0 files)
└── events@0.0.0 9.8 kB (0 files)
└── rxjs@5.5.2 171.6 kB (0 files)
Size: 215.5 kB in 139ms

---------------------------------------------------
Development server running http://localhost:4445
---------------------------------------------------

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/jnaulty/github/muse-js/node_modules/rxjs/operators/publishLast.js ENOSPC
    at exports._errnoException (util.js:1020:11)
    at FSWatcher.start (fs.js:1451:19)
    at Object.fs.watch (fs.js:1478:11)
    at createFsWatchInstance (/home/jnaulty/github/muse-js/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/jnaulty/github/muse-js/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/jnaulty/github/muse-js/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/jnaulty/github/muse-js/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/jnaulty/github/muse-js/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[jnaulty@emarginata muse-js]$ 

```

**Comment by urish** [comment]
`ENOSPC` sounds like you are out of disk space: https://stackoverflow.com/questions/22475849/node-js-error-enospc

**Comment by jnaulty** [comment]
Solution was found here: https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
```
[jnaulty@emarginata muse-js]$ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
[sudo] password for jnaulty: 
fs.inotify.max_user_watches=524288
fs.inotify.max_user_watches = 524288
[jnaulty@emarginata muse-js]$ yarn start
```
Thanks @urish for a speedy response. I'm looking forward to testing this out!
